export default Object.freeze({
  BOOKING_DURATION: "BookingDuration",
  BOOKING_FORM: "BookingForm",
  BOOKING_CONFIRMATION: "BookingConfirmation",
  BOOKINGS_SCREEN: "Bookings",
  BOOKING_SCREEN: "Booking",
  HOTEL_DESCRIPTION: "HotelDescription",
  HOTELS: "Hotels",
  HOME_SCREEN: "HomeScreen",
  HOTEL_DETAILS: "HotelDetails",
  CONFERENCE_HOTEL_DETAILS: "ConferenceHotelDetails",
  APARTMENT_DETAILS: "ApartmentDetails",
  ROOM_DETAILS: "RoomDetails",
  ROOMS: "Rooms",
  CONFERENCE_ROOMS: "ConferenceRooms",
  IMAGES_SCREEN: "ImagesScreen",
  SEARCH_SCREEN: "Search",
  WELCOME_SCREEN: "WelcomeScreen",
  AUTH_NAVIGATOR: "AuthNavigator",
  LOGIN: "Login",
  REGISTER: "Register",
});
